version: '3'
services:
  web:
    image: account_id.dkr.ecr.eu-central-1.amazonaws.com/repo_name:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    logging:
      driver: awslogs
      options: 
        awslogs-group: log_group
        awslogs-region: eu-central-1
        awslogs-stream-prefix: web